{
 "title": "Simple Airflow Test",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total DAGs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_dagbag_size" }
   ]
  },
  {
   "title": "Import Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "airflow_dag_processing_import_errors"
    }
   ]
  },
  {
   "title": "Executor Open Slots",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "airflow_executor_open_slots" }
   ]
  },
  {
   "title": "Tasks Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "airflow_executor_queued_tasks", "legendFormat": "Queued Tasks" },
    { "expr": "airflow_executor_running_tasks", "legendFormat": "Running Tasks" }
   ]
  }
 ]
}