version: '3.8'

services:
  statsd-exporter:
    image: prom/statsd-exporter:latest
    ports:
      - "9102:9102"
      - "8125:9125"
      - "8125:9125/udp"
    command:
      - '--statsd.listen-udp=:9125'
      - '--web.listen-address=:9102'

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./airflow_dashboard.json:/var/lib/grafana/dashboards/airflow_dashboard.json
      - ./dashboard-provider.yml:/etc/grafana/provisioning/dashboards/dashboard-provider.yml
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml