global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Airflow metrics from StatsD exporter
  - job_name: 'airflow-statsd'
    static_configs:
      - targets: ['statsd-exporter:9102']
    scrape_interval: 10s
    metrics_path: /metrics